import { ScanRecord, FarmAlert } from './types';

export const CROP_LIST = [
  { id: 'cotton', nameEn: 'Cotton', nameHi: 'कपास', nameMr: 'कापूस', icon: '🌾' },
  { id: 'wheat', nameEn: 'Wheat', nameHi: 'गेहूं', nameMr: 'गहू', icon: '🌾' },
  { id: 'rice', nameEn: 'Rice / Paddy', nameHi: 'धान / चावल', nameMr: 'भात / धान', icon: '🌾' },
  { id: 'soybean', nameEn: 'Soybean', nameHi: 'सोयाबीन', nameMr: 'सोयाबीन', icon: '🌱' },
  { id: 'tomato', nameEn: 'Tomato', nameHi: 'टमाटर', nameMr: 'टोमॅटो', icon: '🍅' },
  { id: 'potato', nameEn: 'Potato', nameHi: 'आलू', nameMr: 'बटाटा', icon: '🥔' },
  { id: 'maize', nameEn: 'Maize / Corn', nameHi: 'मक्का', nameMr: 'मका', icon: '🌽' },
  { id: 'sugarcane', nameEn: 'Sugarcane', nameHi: 'गन्ना', nameMr: 'ऊस', icon: '🎋' },
  { id: 'onion', nameEn: 'Onion', nameHi: 'प्याज', nameMr: 'कांदा', icon: '🧅' },
  { id: 'chili', nameEn: 'Chili', nameHi: 'मिर्च', nameMr: 'मिरची', icon: '🌶️' },
  { id: 'pulses', nameEn: 'Pulses (Gram/Tur)', nameHi: 'दलहन (चना/अरहर)', nameMr: 'कडधान्ये (हरभरा/तूर)', icon: '🫘' },
  { id: 'fruits', nameEn: 'Fruit Orchard', nameHi: 'फलदार बगीचा', nameMr: 'फळबागा', icon: '🍎' },
  { id: 'vegetables', nameEn: 'Green Vegetables', nameHi: 'हरी सब्जियां', nameMr: 'पालेभाज्या', icon: '🥬' },
  { id: 'other', nameEn: 'Other Field Crop', nameHi: 'अन्य फसल', nameMr: 'इतर पीक', icon: '🌿' },
];

export const ANIMAL_LIST = [
  { id: 'cow', nameEn: 'Cow', nameHi: 'गाय', nameMr: 'गाय', icon: '🐄' },
  { id: 'buffalo', nameEn: 'Buffalo', nameHi: 'भैंस', nameMr: 'म्हैस', icon: '🐃' },
  { id: 'goat', nameEn: 'Goat', nameHi: 'बकरी', nameMr: 'शेळी', icon: '🐐' },
  { id: 'sheep', nameEn: 'Sheep', nameHi: 'भेड़', nameMr: 'मेंढी', icon: '🐑' },
  { id: 'poultry', nameEn: 'Poultry / Chicken', nameHi: 'मुर्गी पालन', nameMr: 'कुक्कुटपालन', icon: '🐔' },
  { id: 'other', nameEn: 'Other Livestock', nameHi: 'अन्य पशु', nameMr: 'इतर पशुधन', icon: '🐾' },
];

export const ANIMAL_SYMPTOMS = [
  { id: 'fever', labelEn: 'Fever / High Body Temp', labelHi: 'बुखार / गर्म शरीर', labelMr: 'ताप / अंग गरम असणे' },
  { id: 'appetite', labelEn: 'Loss of Appetite / Not Feeding', labelHi: 'चारा न खाना / भूख की कमी', labelMr: 'चारा न खाणे / भूक मंदावणे' },
  { id: 'lethargy', labelEn: 'Lethargy / Sluggish Behavior', labelHi: 'सुस्ती / ढीलापन', labelMr: 'मरगळ / सुस्त हालचाल' },
  { id: 'coughing', labelEn: 'Coughing / Breathing Trouble', labelHi: 'खांसी / सांस लेने में तकलीफ', labelMr: 'खोकला / धाप लागणे' },
  { id: 'discharge', labelEn: 'Nasal / Eye Discharge', labelHi: 'नाक/आंख से पानी बहना', labelMr: 'नाक/डोळ्यातून पाणी येणे' },
  { id: 'diarrhea', labelEn: 'Diarrhea / Loose Dung', labelHi: 'दस्त / पतला गोबर', labelMr: 'पातळ शेण / हगवण' },
  { id: 'skin_lesions', labelEn: 'Skin Lesions / Nodules / Lumps', labelHi: 'त्वचा पर गांठें / फोड़े', labelMr: 'त्वचेवर गाठी / फोड' },
  { id: 'swelling', labelEn: 'Udder / Joint Swelling', labelHi: 'थन या जोड़ों में सूजन', labelMr: 'कास किंवा सांधे सुजणे' },
  { id: 'milk_drop', labelEn: 'Reduced Milk Production', labelHi: 'दूध उत्पादन में अचानक गिरावट', labelMr: 'दूध उत्पादनात अचानक घट' },
  { id: 'walking', labelEn: 'Difficulty Walking / Limping', labelHi: 'लंगड़ाना / चलने में कष्ट', labelMr: 'लंगडणे / चालताना त्रास' },
  { id: 'drooling', labelEn: 'Excessive Drooling / Salivation', labelHi: 'मुंह से अधिक लार गिरना', labelMr: 'तोंडातून लाळ गळणे' },
  { id: 'abnormal', labelEn: 'Abnormal Nervous Behavior', labelHi: 'असामान्य आचरण / चक्कर', labelMr: 'विचित्र वर्तन / तोल जाणे' },
];

export const GROWTH_STAGES = [
  { id: 'seedling', labelEn: 'Seedling / Germination', labelHi: 'अंकुरण / छोटा पौधा', labelMr: 'रोपवाटिका / उगवण' },
  { id: 'vegetative', labelEn: 'Vegetative / Branching', labelHi: 'शाकीय वृद्धि (पत्तियां व शाखाएं)', labelMr: 'शाकीय वाढ / फांद्या फुटणे' },
  { id: 'flowering', labelEn: 'Flowering & Budding', labelHi: 'फूल व कलियां निकलना', labelMr: 'फुलोरा अवस्था' },
  { id: 'fruiting', labelEn: 'Fruit / Grain Filling', labelHi: 'फल/दाने भराव अवस्था', labelMr: 'दाणे भरणे / फळे धरणे' },
  { id: 'maturity', labelEn: 'Maturity / Harvest Stage', labelHi: 'परिपक्वता / कटाई पूर्व', labelMr: 'परिपक्वता / काढणी अवस्था' },
];

// Helper to create reliable SVG Data URLs for hackathon demo scans
export function createSvgThumbnail(title: string, subtitle: string, bgColor: string = '#10b981', textColor: string = '#ffffff'): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="240" viewBox="0 0 320 240">
    <rect width="320" height="240" fill="${bgColor}" rx="12"/>
    <circle cx="160" cy="90" r="44" fill="rgba(255,255,255,0.2)"/>
    <path d="M160 60 C140 60 130 85 160 115 C190 85 180 60 160 60 Z" fill="${textColor}" opacity="0.9"/>
    <text x="160" y="160" font-family="system-ui, sans-serif" font-size="18" font-weight="bold" fill="${textColor}" text-anchor="middle">${title}</text>
    <text x="160" y="185" font-family="system-ui, sans-serif" font-size="13" fill="${textColor}" opacity="0.85" text-anchor="middle">${subtitle}</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

// Pre-built Hackathon Samples for instant judge testing
export const HACKATHON_DEMO_SAMPLES = [
  {
    id: 'demo-cotton-spot',
    category: 'crop',
    name: 'Cotton — Leaf Spot (Blight)',
    crop: 'Cotton',
    stage: 'Vegetative',
    symptoms: 'Concentric brown leaf spots, yellow halos',
    image: createSvgThumbnail('Cotton Leaf Blight', 'Fungal Spots Observed', '#d97706'),
    confidence: 93,
    severity: 'Moderate',
  },
  {
    id: 'demo-tomato-early',
    category: 'crop',
    name: 'Tomato — Early Blight (Alternaria)',
    crop: 'Tomato',
    stage: 'Flowering',
    symptoms: 'Target-like rings, lower leaf yellowing',
    image: createSvgThumbnail('Tomato Early Blight', 'Target-board Rings', '#dc2626'),
    confidence: 91,
    severity: 'High',
  },
  {
    id: 'demo-wheat-healthy',
    category: 'crop',
    name: 'Wheat — Healthy Canopy',
    crop: 'Wheat',
    stage: 'Fruiting',
    symptoms: 'None, vigorous green leaf blades',
    image: createSvgThumbnail('Healthy Wheat', 'Clear & Vigorous', '#059669'),
    confidence: 96,
    severity: 'Low',
  },
  {
    id: 'demo-cow-lumpy',
    category: 'animal',
    name: 'Cow — Suspected Lumpy Skin Screening',
    animal: 'Cow',
    symptoms: ['Fever / High Body Temp', 'Loss of Appetite / Not Feeding', 'Skin Lesions / Nodules / Lumps'],
    image: createSvgThumbnail('Cow Dermal Lesions', 'Nodular Signs Screening', '#b91c1c'),
    confidence: 89,
    severity: 'High',
  },
  {
    id: 'demo-buffalo-mastitis',
    category: 'animal',
    name: 'Buffalo — Mastitis / Udder Alert',
    animal: 'Buffalo',
    symptoms: ['Udder / Joint Swelling', 'Reduced Milk Production', 'Fever / High Body Temp'],
    image: createSvgThumbnail('Buffalo Udder Alert', 'Swelling & Drop in Yield', '#ea580c'),
    confidence: 94,
    severity: 'High',
  },
  {
    id: 'demo-poultry-heat',
    category: 'animal',
    name: 'Poultry — Heat Stress Screening',
    animal: 'Poultry / Chicken',
    symptoms: ['Lethargy / Sluggish Behavior', 'Coughing / Breathing Trouble'],
    image: createSvgThumbnail('Poultry Flock', 'Panting & Heat Stress', '#d97706'),
    confidence: 87,
    severity: 'Moderate',
  },
];

// Seed scan history for instant rich dashboard and history view
export const INITIAL_SCAN_HISTORY: ScanRecord[] = [
  {
    id: 'scan-1',
    type: 'crop',
    date: '2026-09-11 08:30 AM',
    entityName: 'Cotton',
    condition: 'Cercospora Leaf Spot',
    confidence: 92,
    severity: 'Moderate',
    imageThumbnail: createSvgThumbnail('Cotton Leaf', 'Cercospora Spot Detected', '#d97706'),
    isHealthy: false,
    cropData: {
      id: 'scan-1',
      timestamp: '2026-09-11 08:30 AM',
      imageQualityValid: true,
      clarityFeedback: 'Clear focus on leaf surface with adequate sunlight.',
      cropIdentified: 'Cotton (Gossypium hirsutum)',
      conditionName: 'Cercospora Leaf Spot',
      isHealthy: false,
      confidenceScore: 92,
      severityLevel: 'Moderate',
      visibleSymptoms: ['Circular reddish-brown necrotic spots', 'Concentric rings with pale grey centers', 'Slight leaf margin curling'],
      possibleCauses: ['Foliar fungal spore germination favored by morning dew and warm midday temperatures', 'Dense crop canopy restricting airflow'],
      whyAiFlaggedThis: ['Concentric ring patterns characteristic of Cercospora fungus', 'Surrounding chlorotic yellow margins confirm active pathogenesis', 'Visual lesion density ~18% of leaf area'],
      immediateActions: ['Remove and bury heavily infected lower leaves', 'Avoid sprinkler irrigation during late evening hours', 'Apply bio-fungicide Pseudomonas fluorescens or Neem seed kernel extract (5%)'],
      preventionTips: ['Ensure 90cm row spacing for optimal sunlight penetration', 'Balance nitrogen application with adequate potash to reinforce leaf cell walls'],
      expertAssistanceRecommendation: 'Monitor for 48 hours; if spotting advances to upper bolls, consult local Krishi Vigyan Kendra.',
      imageThumbnail: createSvgThumbnail('Cotton Leaf', 'Cercospora Spot Detected', '#d97706'),
      growthStage: 'Vegetative',
      location: 'Plot 2 - East Field',
    },
  },
  {
    id: 'scan-2',
    type: 'animal',
    date: '2026-09-10 04:15 PM',
    entityName: 'Cow',
    condition: 'Suspected Lumpy Skin Disease (LSD) Screening Alert',
    confidence: 89,
    severity: 'High',
    imageThumbnail: createSvgThumbnail('Cow Inspection', 'Dermal Nodules Flagged', '#b91c1c'),
    isHealthy: false,
    animalData: {
      id: 'scan-2',
      timestamp: '2026-09-10 04:15 PM',
      animalType: 'Gir Cow',
      possibleCondition: 'Suspected Lumpy Skin Disease (LSD) Screening Alert',
      isHealthy: false,
      riskLevel: 'High',
      confidenceScore: 89,
      observedIndicators: ['Multiple firm round nodular skin eruptions (2–5 cm diameter)', 'Reported high body temperature (>104°F)', 'Marked drop in dry fodder intake and salivation'],
      whyAiFlaggedThis: ['Distinct circumscribed cutaneous nodules along neck and flank', 'Combination of fever with sudden anorexia aligns with capripoxvirus indicators', 'Regional vector activity reported in surrounding taluka'],
      immediateSafeActions: ['Isolate this cow immediately in an airy, fly-proof enclosure at least 50 meters from other cattle', 'Provide cool drinking water mixed with jaggery and electrolytes', 'Use mosquito nets and spray organic neem repellent around the shed'],
      preventionAndHygiene: ['Disinfect shed floor and feeding mangers with 1% Virkon or 2% sodium hypochlorite', 'Do not share common grazing areas or water troughs'],
      veterinaryConsultationRequired: true,
      veterinaryAdvice: 'Urgent veterinary intervention is required. Contact government veterinary officer immediately for formal blood sampling and goat pox vaccination verification.',
      safetyDisclaimer: 'FarmGuard AI is an early screening and decision-support tool, NOT a certified veterinary diagnosis.',
      imageThumbnail: createSvgThumbnail('Cow Inspection', 'Dermal Nodules Flagged', '#b91c1c'),
      reportedSymptoms: ['Skin Lesions / Nodules / Lumps', 'Fever / High Body Temp', 'Loss of Appetite / Not Feeding'],
      notes: 'Cow stopped feeding yesterday afternoon; bumps appeared on neck this morning.',
    },
  },
  {
    id: 'scan-3',
    type: 'crop',
    date: '2026-09-09 11:00 AM',
    entityName: 'Tomato',
    condition: 'Early Blight (Alternaria solani)',
    confidence: 94,
    severity: 'Moderate',
    imageThumbnail: createSvgThumbnail('Tomato Leaf', 'Target Spots Flagged', '#ea580c'),
    isHealthy: false,
    cropData: {
      id: 'scan-3',
      timestamp: '2026-09-09 11:00 AM',
      imageQualityValid: true,
      clarityFeedback: 'Sharp focus on lower leaf cluster.',
      cropIdentified: 'Tomato (Solanum lycopersicum)',
      conditionName: 'Early Blight (Alternaria solani)',
      isHealthy: false,
      confidenceScore: 94,
      severityLevel: 'Moderate',
      visibleSymptoms: ['Concentric dark brown bullseye spots', 'Lower leaf senescence and yellowing'],
      possibleCauses: ['Alternaria fungus surviving on crop residues', 'Warm humid micro-climate near soil level'],
      whyAiFlaggedThis: ['Classic target-board pattern on older leaves', 'Progressive yellowing spreading upwards from lowest leaves'],
      immediateActions: ['Trim off yellowed lower leaves touching moist soil', 'Apply copper hydroxide spray or Trichoderma viride bio-agent'],
      preventionTips: ['Stake tomato vines to keep leaves dry and above soil', 'Practice 3-year crop rotation avoiding solanaceous crops'],
      expertAssistanceRecommendation: 'If fruit calyx exhibits black sunken lesions, seek fungicide guidance from KVK.',
      imageThumbnail: createSvgThumbnail('Tomato Leaf', 'Target Spots Flagged', '#ea580c'),
      growthStage: 'Flowering',
      location: 'Greenhouse Bed A',
    },
  },
  {
    id: 'scan-4',
    type: 'crop',
    date: '2026-09-08 09:20 AM',
    entityName: 'Wheat',
    condition: 'Healthy Canopy — No Pathogens Detected',
    confidence: 97,
    severity: 'Low',
    imageThumbnail: createSvgThumbnail('Wheat Field', 'Healthy Vigorous Foliage', '#059669'),
    isHealthy: true,
    cropData: {
      id: 'scan-4',
      timestamp: '2026-09-08 09:20 AM',
      imageQualityValid: true,
      clarityFeedback: 'Excellent lighting and resolution.',
      cropIdentified: 'Wheat (Triticum aestivum)',
      conditionName: 'Healthy Canopy — No Pathogens Detected',
      isHealthy: true,
      confidenceScore: 97,
      severityLevel: 'Low',
      visibleSymptoms: ['Deep emerald green foliage', 'Turgid erect leaf blades', 'No rust pustules or powdery lesions'],
      possibleCauses: ['Adequate nitrogen and moisture balance', 'Beneficial solar radiation'],
      whyAiFlaggedThis: ['Uniform spectral chlorophyll distribution', 'Clean vein structure and absence of chlorosis or fungal pustules'],
      immediateActions: ['Continue standard irrigation scheduling', 'Monitor flag leaves twice weekly during heading stage'],
      preventionTips: ['Maintain protective bio-fertilizer schedule (Azotobacter & PSB)'],
      expertAssistanceRecommendation: 'Routine check is satisfactory. No escalation required.',
      imageThumbnail: createSvgThumbnail('Wheat Field', 'Healthy Vigorous Foliage', '#059669'),
      growthStage: 'Fruiting',
      location: 'North Acre',
    },
  },
];

export const INITIAL_FARM_ALERTS: FarmAlert[] = [
  {
    id: 'alert-1',
    title: 'High Risk: Suspected Lumpy Skin Disease Screening',
    category: 'livestock',
    severity: 'high',
    timestamp: 'Yesterday, 04:15 PM',
    description: 'Gir Cow in Stall #2 flagged with high probability cutaneous nodule pattern. Quarantine advised.',
    actionRequired: 'Keep animal isolated; notify local veterinary hospital for confirmation.',
  },
  {
    id: 'alert-2',
    title: 'High Humidity Weather Warning: Fungal Disease Spore Germination',
    category: 'weather',
    severity: 'warning',
    timestamp: 'Today, 06:00 AM',
    description: 'Relative humidity reaching 84% with intermittent mist. High risk for Cotton leaf spot and Tomato early blight.',
    actionRequired: 'Ensure drainage trenches are clear. Delay excessive nitrogen fertilization.',
  },
  {
    id: 'alert-3',
    title: 'Livestock Deworming & Vaccination Reminder',
    category: 'reminder',
    severity: 'info',
    timestamp: 'Sep 15 Scheduled',
    description: 'Quarterly FMD (Foot-and-Mouth) booster vaccination campaign scheduled by Block Veterinary Dispensary.',
    actionRequired: 'Register herd count with Village Gram Sevak.',
  },
];

// Offline Compendium for Farmers when completely off-grid
export const OFFLINE_EDUCATIONAL_LIBRARY = [
  {
    id: 'lib-1',
    category: 'crop',
    title: 'Cotton: Cercospora & Alternaria Leaf Spots',
    symptoms: 'Circular brownish spots with ash-colored centers, concentric rings, premature leaf drop.',
    organicRemedy: 'Spray Neem oil @ 5ml/liter with 1g soap nut liquid. Ensure good aeration.',
    chemicalControl: 'Mancozeb 75 WP @ 2g/liter or Copper Oxychloride @ 3g/liter under expert supervision.',
    prevention: 'Deep summer ploughing, destroy crop residues, maintain recommended plant density.',
  },
  {
    id: 'lib-2',
    category: 'crop',
    title: 'Tomato: Early & Late Blight Management',
    symptoms: 'Target-like rings on lower leaves, brown stem lesions, dark water-soaked fruit spots.',
    organicRemedy: 'Foliar spray of butter-milk (chhaas) fermented 5 days with asafoetida (hing) diluted 1:10.',
    chemicalControl: 'Metalaxyl + Mancozeb @ 2g/L or Chlorothalonil @ 2g/L.',
    prevention: 'Staking of vines, plastic mulching, strictly avoid sprinkler/overhead watering.',
  },
  {
    id: 'lib-3',
    category: 'crop',
    title: 'Wheat: Yellow & Brown Rust Identification',
    symptoms: 'Linear yellow stripes or scattered brown pustules on leaf surface that leave rust dust on fingers.',
    organicRemedy: 'Spray liquid Trichoderma viride @ 5ml/liter early in the morning.',
    chemicalControl: 'Propiconazole 25 EC @ 1ml/liter upon initial symptom notice.',
    prevention: 'Cultivate rust-resistant varieties recommended by ICAR for your agro-climatic zone.',
  },
  {
    id: 'lib-4',
    category: 'livestock',
    title: 'Cattle: Lumpy Skin Disease (LSD) First-Aid & Bio-Security',
    symptoms: 'Nodules of 2-5cm over body, high fever, swollen lymph nodes, loss of milk.',
    firstAid: 'Immediate strict isolation. Clean water with electrolyte/jaggery. Fly-proofing with neem leaves.',
    veterinaryNote: 'Notify Veterinary Officer immediately. Do NOT lance or puncture the skin nodules.',
    prevention: 'Annual Goat Pox vaccination. Spray safe insecticides on shed boundaries to control ticks and flies.',
  },
  {
    id: 'lib-5',
    category: 'livestock',
    title: 'Buffalo & Cow: Mastitis (Thaila) Early Detection',
    symptoms: 'Swollen, warm, tender udder; clots, flakes, or watery discolored milk.',
    firstAid: 'Cold water compression for acute heat. Strip milk out cleanly 4 times daily. Keep stall dry.',
    veterinaryNote: 'Intramammary antibiotic infusion strictly as prescribed by a licensed veterinarian.',
    prevention: 'Teat dipping in 0.5% povidone-iodine post-milking. Never allow animals to lie on wet dung.',
  },
  {
    id: 'lib-6',
    category: 'livestock',
    title: 'Goat & Sheep: Ruminal Bloat (Afra / Tympany)',
    symptoms: 'Distended left flank drum-tight, distress, restlessness, rapid breathing.',
    firstAid: 'Keep head elevated. Administer 100-150ml edible mustard or peanut oil with 5ml ginger juice.',
    veterinaryNote: 'If animal collapses or groans heavily, immediate veterinary trocharization needed.',
    prevention: 'Do not graze hungry animals on dew-covered young legumes or wilted sorghum.',
  },
];
